version: "3.8"

services:
  frontend:
    image: ${FRONTEND_IMAGE_URI_WITH_TAG}
    ports:
      - "3000:80" # Map host port 3000 to container port 80 (Nginx default)
    # If the frontend needs to know the backend's URL via an env var in the future, add it here.
    # environment:
    #   - VITE_API_BASE_URL=http://backend:3001
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - kudos_wall_network

  backend:
    image: ${BACKEND_IMAGE_URI_WITH_TAG}
    ports:
      - "3001:3001" # Map host port 3001 to container port 3001 (backend's internal port)
    environment:
      - PORT=3001
      - NODE_ENV=test
      - DATABASE_URL=file:/app/prisma/test.db
      - DEBUG=*
    volumes:
      - ./backend-data/prisma:/app/prisma
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 45s
    networks:
      - kudos_wall_network
    command: >
      /bin/sh -c "
        npx prisma migrate deploy &&
        node dist/index.js
      "

networks:
  kudos_wall_network:
    driver: bridge
volumes:
  backend_data:

