version: "3.8"

services:
  frontend:
    image: ${FRONTEND_IMAGE_URI_WITH_TAG}
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - kudos_wall_network

  backend:
    image: ${BACKEND_IMAGE_URI_WITH_TAG}
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=test
      - DATABASE_URL=file:/app/prisma/test.db
      - DEBUG=*
    volumes:
      - ./backend-data/prisma:/app/prisma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 45s
    networks:
      - kudos_wall_network
    command: >
      sh -c "
        npx prisma migrate deploy &&
        exec node dist/index.js
      "

networks:
  kudos_wall_network:
    driver: bridge
volumes:
  backend_data:
