version: "3.8"

services:
  frontend:
    image: ghcr.io/chirag1507/digital-kudos-wall-frontend:latest
    ports:
      - "3000:80" # Map host port 3000 to container port 80 (Nginx default)
    # If the frontend needs to know the backend's URL via an env var in the future, add it here.
    # environment:
    #   - VITE_API_BASE_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - kudos_wall_network

  backend:
    build:
      context: ../digital-kudos-wall-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Map host port 3001 to container port 3001 (backend's internal port)
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DATABASE_URL=file:/data/dev.db
    networks:
      - kudos_wall_network
    volumes:
      - backend_data:/data

networks:
  kudos_wall_network:
    driver: bridge

volumes:
  backend_data:
